on:
  push:
    branches: ['main']
    paths:
      - "ansible-roles-qa/**"
      - '.github/workflows/ansible-roles.yml'
jobs:
  publish-container:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ansible-roles-qa --file ansible-roles-qa/Dockerfile --tag ansible-roles-qa:$(date +%s)