name: 'Ansible Roles QA Container'
on:
  push:
    branches: ['main']
    paths:
      - "ansible-roles-qa/**"
      - '.github/workflows/ansible-roles.yml'
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: curium-rocks/ansible-roles-qa
jobs:
  publish-container:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@25c0ca8bab9893f0962d4ffd043f2b7ab90e9a3f
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@6d43bfb301c5ed182a59cfa3b21916868c62c405
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      uses: docker/build-push-action@04d5124fcbe023bf2106e1fea7c1b30717c7fc32
      with:
        context: ansible-roles-qa
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}